version: '3'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
    db:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
