version: '3.8'

services:
    backend:
        build: .
        ports:
            - '8080:8080'
        environment:
            - NODE_ENV=production
            - PORT=8080
        restart: unless-stopped
