name: CI/CD for Node.js Backend

on:
    push:
        branches: [master] # You can change this to 'master' or any branch you want

jobs:
    backend-deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./Backend # Specify the subfolder

        steps:
            - name: 📦 Checkout code
              uses: actions/checkout@v3

            - name: 🧰 Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: 📥 Install dependencies
              run: npm install

            - name: 🧪 Run tests
              run: npm test || echo "No tests yet"

            - name: 🚀 Trigger Deploy on Render
              run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
